include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # --- Style & Readability ---
    prefer_single_quotes: true
    always_use_package_imports: true
    avoid_print: true
    avoid_unnecessary_containers: true
    unnecessary_lambdas: true

    # --- Safety & Best Practices ---
    avoid_dynamic_calls: true
    avoid_void_async: true
    cancel_subscriptions: true
    close_sinks: true
    use_build_context_synchronously: true

    # --- Flutter-specific ---
    sized_box_for_whitespace: true
    use_key_in_widget_constructors: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
